INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_LMS_EQUALISER lms_equaliser)

FIND_PATH(
    LMS_EQUALISER_INCLUDE_DIRS
    NAMES lms_equaliser/api.h
    HINTS $ENV{LMS_EQUALISER_DIR}/include
        ${PC_LMS_EQUALISER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    LMS_EQUALISER_LIBRARIES
    NAMES gnuradio-lms_equaliser
    HINTS $ENV{LMS_EQUALISER_DIR}/lib
        ${PC_LMS_EQUALISER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LMS_EQUALISER DEFAULT_MSG LMS_EQUALISER_LIBRARIES LMS_EQUALISER_INCLUDE_DIRS)
MARK_AS_ADVANCED(LMS_EQUALISER_LIBRARIES LMS_EQUALISER_INCLUDE_DIRS)

